import { Achievement } from '@/src/types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_quiz',
    name: 'First Steps',
    description: 'Complete your first quiz',
    icon: 'star',
    xp_reward: 50,
    condition_type: 'quizzes_completed',
    condition_value: 1,
  },
  {
    id: 'first_pass',
    name: 'Passed!',
    description: 'Pass your first mock exam',
    icon: 'trophy',
    xp_reward: 200,
    condition_type: 'mock_exams_passed',
    condition_value: 1,
  },
  {
    id: 'perfect_score',
    name: 'Perfectionist',
    description: 'Get a perfect score on a mock exam',
    icon: 'crown',
    xp_reward: 500,
    condition_type: 'perfect_mock_exams',
    condition_value: 1,
  },
  {
    id: 'streak_3',
    name: 'Getting Started',
    description: 'Maintain a 3-day streak',
    icon: 'flame',
    xp_reward: 30,
    condition_type: 'streak_days',
    condition_value: 3,
  },
  {
    id: 'streak_7',
    name: 'On a Roll',
    description: 'Maintain a 7-day streak',
    icon: 'flame',
    xp_reward: 100,
    condition_type: 'streak_days',
    condition_value: 7,
  },
  {
    id: 'streak_30',
    name: 'Dedicated Learner',
    description: 'Maintain a 30-day streak',
    icon: 'flame',
    xp_reward: 500,
    condition_type: 'streak_days',
    condition_value: 30,
  },
  {
    id: 'questions_50',
    name: 'Half Century',
    description: 'Answer 50 questions',
    icon: 'target',
    xp_reward: 100,
    condition_type: 'questions_answered',
    condition_value: 50,
  },
  {
    id: 'questions_100',
    name: 'Century',
    description: 'Answer 100 questions',
    icon: 'target',
    xp_reward: 200,
    condition_type: 'questions_answered',
    condition_value: 100,
  },
  {
    id: 'questions_500',
    name: 'Knowledge Seeker',
    description: 'Answer 500 questions',
    icon: 'target',
    xp_reward: 500,
    condition_type: 'questions_answered',
    condition_value: 500,
  },
  {
    id: 'all_topics',
    name: 'Well Rounded',
    description: 'Study all topics',
    icon: 'book-open',
    xp_reward: 300,
    condition_type: 'topics_studied',
    condition_value: 999, // Will be set dynamically
  },
  {
    id: 'accuracy_80',
    name: 'Sharp Mind',
    description: 'Achieve 80% overall accuracy',
    icon: 'brain',
    xp_reward: 200,
    condition_type: 'overall_accuracy',
    condition_value: 80,
  },
  {
    id: 'xp_1000',
    name: 'Experienced',
    description: 'Earn 1000 XP',
    icon: 'zap',
    xp_reward: 100,
    condition_type: 'total_xp',
    condition_value: 1000,
  },
];
